### ISSUE TITLE
realtime

### ISSUE THREAD

**Issue by rito** [codingfriend1/Feathers-Vue#3]
It's possible change to a realtime application?
how can I change to connect in feathers to use socket api ?

**Comment by codingfriend1** [comment]
It should automatically connect to feathers using sockets as long as you are making api requests client side. You can see the feathers.service.js and sync.list.service. If you are making api requests server side it will use axios. Take a look at the services/api/ folder. This is for if you want to retrieve information for server side rendering before you render the page.

```
.configure(socketio(socket))
```

**Comment by rito** [comment]
I understood that it would work automatically. But it was not what I expected. So, I think, I dont understand correctly.
I started the project, log in and Add a message. After that, I went to MongoDB and changed the same message. This information is not reflected on the screen. I'm forced to refresh the screen. :(

**Comment by codingfriend1** [comment]
I don't believe real time watches the database for changes, it builds off of events generated by the server or API events. So you would have to change the message through something like postman where you are making an API request.

**Comment by rito** [comment]
Thanks.
I will think about. This resolves 80% for my solution. I will study your project. Thanks.
