### ISSUE TITLE
Couldn't find env file

### ISSUE THREAD

**Issue by gathrlabs** [codingfriend1/Feathers-Vue#4]
This is a great project, with a lot of awesome functionality. Thanks!

I was interested in being able to stand this up using docker so I ran the 

`docker-compose up` command. 

This threw an error:
"Couldn't find env file"

**Comment by codingfriend1** [comment]
Thanks for pointing this out. You have to create that file yourself because it shouldn't be included in git as it may contain sensitive information. It holds your production environment variables. I've updated the readme instructions.

**Comment by gathrlabs** [comment]
Perfect. That seems pretty obvious now. I'll close this off.
