### ISSUE TITLE
Please make it possible to use with other DB backends

### ISSUE THREAD

**Issue by COLABORATI** [codingfriend1/Feathers-Vue#8]
Hi, feathers is a great project - what makes it so great is the fact that it is database agnostic. 
This project looks also very interesting - however, you drop one of the main selling points for feathers by fixating on one backend DB. It would be a great step towards more "featherness" if you tried to implement this boilerplate in a DB agnostic way! 
Thank you very much!

**Comment by codingfriend1** [comment]
That's fair. I liked the fact that with mongodb you could use 1 schema to validate both client and server side. Perhaps I'll start a new branch and use a different validation library.

Do you have any recommendations on a validation library?

**Comment by codingfriend1** [comment]
I have a new branch called database-agnostic. I haven't thoroughly tested it, but it seems to be working. Will play with it more when I have time. It removes the client side mongoose validation and replaces it with yup. It should be safe to change out the database now but I'll test more later.
